park:
    customers: 2
    customers-cash: 20.0
    capacity: 2
    games-cost:
        - 10.0
        - 10.0
        - 10.0
        - 10.0
        - 10.0
        - 10.0
        - 20.0
        - 30.0
    debug: false